name: Deploy App

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HOST: ubuntu@13.61.178.171
      DEPLOY_DIRECTORY: /home/ubuntu/ai-marketplace
      ENV_FILE_PATH: /home/ubuntu/ai-marketplace/.env

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Check if tag exists
        run: |
          git fetch --all --tags
          if ! git tag | grep -q "^${{ github.event.inputs.tag }}$"; then
            echo "error: Tag '${{ github.event.inputs.tag }}' not found"
            exit 1
          fi

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.24.0

      - name: Build app
        run: |
          go mod tidy
          go mod download
          go build -o ai-marketplace ./cmd/server

      - name: Deploy to VM
        run: |
          sudo apt-get install -y ssh rsync
          echo "$DEPLOY_SSH_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} "mkdir -p ${{ env.DEPLOY_DIRECTORY }}"
          rsync -avz -e 'ssh -i deploy_key.pem -o StrictHostKeyChecking=no' --exclude='.git' ./ ${{ env.HOST }}:${{ env.DEPLOY_DIRECTORY }}
        env:
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Create .env file
        run: |
          echo "PORT=${{ secrets.PORT }}" > .env
          echo "GOOGLE_SEARCH_API_KEY=${{ secrets.GOOGLE_SEARCH_API_KEY }}" >> .env
          echo "GOOGLE_SEARCH_CX=${{ secrets.GOOGLE_SEARCH_CX }}" >> .env
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env

      - name: Copy .env to server
        run: |
          scp -i deploy_key.pem -o StrictHostKeyChecking=no .env ${{ env.HOST }}:${{ env.ENV_FILE_PATH }}

      - name: Upload systemd service file
        run: |
          scp -i deploy_key.pem -o StrictHostKeyChecking=no \
            ${{ github.workspace }}/deployment/ai-marketplace.service \
            ${{ env.HOST }}:/tmp/ai-marketplace.service

      - name: Move service file to systemd directory
        run: |
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} "\
            sudo mv /tmp/ai-marketplace.service /etc/systemd/system/ai-marketplace.service && \
            sudo chown root:root /etc/systemd/system/ai-marketplace.service && \
            sudo chmod 644 /etc/systemd/system/ai-marketplace.service"

      - name: Restart service
        run: |
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} "\
            sudo systemctl daemon-reload && \
            sudo systemctl enable ai-marketplace.service && \
            sudo systemctl restart ai-marketplace.service && \
            sudo systemctl status ai-marketplace.service"